# Generated by Django 2.2.3 on 2019-07-19 14:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Task Title')),
                ('description', models.TextField(verbose_name='Task Description')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'New'), (1, 'In Progress'), (2, 'Done')], default=0, verbose_name='Task State')),
                ('linked_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_tasks', to='tasks.Task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
